version: 2
jobs:
  build:
  
    docker:
      - image: ruby:2.6.3
        
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle_ci_example-{{ checksum "Gemfile.lock" }}
            - circle_ci_example-
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle

      - save_cache:
          key: circle_ci_example-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: bundle exec rspec
